"""empty message

Revision ID: 68e43bfce6ab
Revises: 562bd5f1bc1f
Create Date: 2020-07-19 16:13:56.748829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e43bfce6ab'
down_revision = '562bd5f1bc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('officer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('star_no', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('star_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('resign_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_assignments_version_end_transaction_id'), 'assignments_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_assignments_version_operation_type'), 'assignments_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_assignments_version_resign_date'), 'assignments_version', ['resign_date'], unique=False)
    op.create_index(op.f('ix_assignments_version_star_date'), 'assignments_version', ['star_date'], unique=False)
    op.create_index(op.f('ix_assignments_version_star_no'), 'assignments_version', ['star_no'], unique=False)
    op.create_index(op.f('ix_assignments_version_transaction_id'), 'assignments_version', ['transaction_id'], unique=False)
    op.create_table('descriptions_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('text_contents', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('officer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_descriptions_version_end_transaction_id'), 'descriptions_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_descriptions_version_operation_type'), 'descriptions_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_descriptions_version_transaction_id'), 'descriptions_version', ['transaction_id'], unique=False)
    op.create_table('faces_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('officer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('img_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('original_image_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('face_position_x', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('face_position_y', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('face_width', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('face_height', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_faces_version_end_transaction_id'), 'faces_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_faces_version_operation_type'), 'faces_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_faces_version_transaction_id'), 'faces_version', ['transaction_id'], unique=False)
    op.create_table('incident_license_plates_version',
    sa.Column('incident_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('license_plate_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id', 'license_plate_id', 'transaction_id')
    )
    op.create_index(op.f('ix_incident_license_plates_version_end_transaction_id'), 'incident_license_plates_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_incident_license_plates_version_operation_type'), 'incident_license_plates_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_incident_license_plates_version_transaction_id'), 'incident_license_plates_version', ['transaction_id'], unique=False)
    op.create_table('incident_links_version',
    sa.Column('incident_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('link_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id', 'link_id', 'transaction_id')
    )
    op.create_index(op.f('ix_incident_links_version_end_transaction_id'), 'incident_links_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_incident_links_version_operation_type'), 'incident_links_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_incident_links_version_transaction_id'), 'incident_links_version', ['transaction_id'], unique=False)
    op.create_table('incidents_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('time', sa.Time(), autoincrement=False, nullable=True),
    sa.Column('report_number', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_updated_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_incidents_version_date'), 'incidents_version', ['date'], unique=False)
    op.create_index(op.f('ix_incidents_version_end_transaction_id'), 'incidents_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_incidents_version_operation_type'), 'incidents_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_incidents_version_report_number'), 'incidents_version', ['report_number'], unique=False)
    op.create_index(op.f('ix_incidents_version_time'), 'incidents_version', ['time'], unique=False)
    op.create_index(op.f('ix_incidents_version_transaction_id'), 'incidents_version', ['transaction_id'], unique=False)
    op.create_table('links_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('url', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('link_type', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('author', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_links_version_end_transaction_id'), 'links_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_links_version_link_type'), 'links_version', ['link_type'], unique=False)
    op.create_index(op.f('ix_links_version_operation_type'), 'links_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_links_version_title'), 'links_version', ['title'], unique=False)
    op.create_index(op.f('ix_links_version_transaction_id'), 'links_version', ['transaction_id'], unique=False)
    op.create_table('notes_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('text_contents', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('officer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_notes_version_end_transaction_id'), 'notes_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_notes_version_operation_type'), 'notes_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_notes_version_transaction_id'), 'notes_version', ['transaction_id'], unique=False)
    op.create_table('officer_incidents_version',
    sa.Column('officer_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('officer_id', 'incident_id', 'transaction_id')
    )
    op.create_index(op.f('ix_officer_incidents_version_end_transaction_id'), 'officer_incidents_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_officer_incidents_version_operation_type'), 'officer_incidents_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_officer_incidents_version_transaction_id'), 'officer_incidents_version', ['transaction_id'], unique=False)
    op.create_table('officer_links_version',
    sa.Column('officer_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('link_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('officer_id', 'link_id', 'transaction_id')
    )
    op.create_index(op.f('ix_officer_links_version_end_transaction_id'), 'officer_links_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_officer_links_version_operation_type'), 'officer_links_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_officer_links_version_transaction_id'), 'officer_links_version', ['transaction_id'], unique=False)
    op.create_table('officers_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('middle_initial', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('suffix', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('race', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('gender', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('employment_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('birth_year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('unique_internal_identifier', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_officers_version_birth_year'), 'officers_version', ['birth_year'], unique=False)
    op.create_index(op.f('ix_officers_version_employment_date'), 'officers_version', ['employment_date'], unique=False)
    op.create_index(op.f('ix_officers_version_end_transaction_id'), 'officers_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_officers_version_first_name'), 'officers_version', ['first_name'], unique=False)
    op.create_index(op.f('ix_officers_version_gender'), 'officers_version', ['gender'], unique=False)
    op.create_index(op.f('ix_officers_version_last_name'), 'officers_version', ['last_name'], unique=False)
    op.create_index(op.f('ix_officers_version_operation_type'), 'officers_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_officers_version_race'), 'officers_version', ['race'], unique=False)
    op.create_index(op.f('ix_officers_version_suffix'), 'officers_version', ['suffix'], unique=False)
    op.create_index(op.f('ix_officers_version_transaction_id'), 'officers_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_officers_version_unique_internal_identifier'), 'officers_version', ['unique_internal_identifier'], unique=False)
    op.create_table('salaries_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('officer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.Numeric(), autoincrement=False, nullable=True),
    sa.Column('overtime_pay', sa.Numeric(), autoincrement=False, nullable=True),
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_fiscal_year', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_salaries_version_end_transaction_id'), 'salaries_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_salaries_version_operation_type'), 'salaries_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_salaries_version_overtime_pay'), 'salaries_version', ['overtime_pay'], unique=False)
    op.create_index(op.f('ix_salaries_version_salary'), 'salaries_version', ['salary'], unique=False)
    op.create_index(op.f('ix_salaries_version_transaction_id'), 'salaries_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_salaries_version_year'), 'salaries_version', ['year'], unique=False)
    op.create_table('unit_types_version',
    sa.Column('id', sa.String(length=120), autoincrement=False, nullable=False),
    sa.Column('descrip', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_unit_types_version_descrip'), 'unit_types_version', ['descrip'], unique=False)
    op.create_index(op.f('ix_unit_types_version_end_transaction_id'), 'unit_types_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_unit_types_version_operation_type'), 'unit_types_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_unit_types_version_transaction_id'), 'unit_types_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_unit_types_version_transaction_id'), table_name='unit_types_version')
    op.drop_index(op.f('ix_unit_types_version_operation_type'), table_name='unit_types_version')
    op.drop_index(op.f('ix_unit_types_version_end_transaction_id'), table_name='unit_types_version')
    op.drop_index(op.f('ix_unit_types_version_descrip'), table_name='unit_types_version')
    op.drop_table('unit_types_version')
    op.drop_index(op.f('ix_salaries_version_year'), table_name='salaries_version')
    op.drop_index(op.f('ix_salaries_version_transaction_id'), table_name='salaries_version')
    op.drop_index(op.f('ix_salaries_version_salary'), table_name='salaries_version')
    op.drop_index(op.f('ix_salaries_version_overtime_pay'), table_name='salaries_version')
    op.drop_index(op.f('ix_salaries_version_operation_type'), table_name='salaries_version')
    op.drop_index(op.f('ix_salaries_version_end_transaction_id'), table_name='salaries_version')
    op.drop_table('salaries_version')
    op.drop_index(op.f('ix_officers_version_unique_internal_identifier'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_transaction_id'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_suffix'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_race'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_operation_type'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_last_name'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_gender'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_first_name'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_end_transaction_id'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_employment_date'), table_name='officers_version')
    op.drop_index(op.f('ix_officers_version_birth_year'), table_name='officers_version')
    op.drop_table('officers_version')
    op.drop_index(op.f('ix_officer_links_version_transaction_id'), table_name='officer_links_version')
    op.drop_index(op.f('ix_officer_links_version_operation_type'), table_name='officer_links_version')
    op.drop_index(op.f('ix_officer_links_version_end_transaction_id'), table_name='officer_links_version')
    op.drop_table('officer_links_version')
    op.drop_index(op.f('ix_officer_incidents_version_transaction_id'), table_name='officer_incidents_version')
    op.drop_index(op.f('ix_officer_incidents_version_operation_type'), table_name='officer_incidents_version')
    op.drop_index(op.f('ix_officer_incidents_version_end_transaction_id'), table_name='officer_incidents_version')
    op.drop_table('officer_incidents_version')
    op.drop_index(op.f('ix_notes_version_transaction_id'), table_name='notes_version')
    op.drop_index(op.f('ix_notes_version_operation_type'), table_name='notes_version')
    op.drop_index(op.f('ix_notes_version_end_transaction_id'), table_name='notes_version')
    op.drop_table('notes_version')
    op.drop_index(op.f('ix_links_version_transaction_id'), table_name='links_version')
    op.drop_index(op.f('ix_links_version_title'), table_name='links_version')
    op.drop_index(op.f('ix_links_version_operation_type'), table_name='links_version')
    op.drop_index(op.f('ix_links_version_link_type'), table_name='links_version')
    op.drop_index(op.f('ix_links_version_end_transaction_id'), table_name='links_version')
    op.drop_table('links_version')
    op.drop_index(op.f('ix_incidents_version_transaction_id'), table_name='incidents_version')
    op.drop_index(op.f('ix_incidents_version_time'), table_name='incidents_version')
    op.drop_index(op.f('ix_incidents_version_report_number'), table_name='incidents_version')
    op.drop_index(op.f('ix_incidents_version_operation_type'), table_name='incidents_version')
    op.drop_index(op.f('ix_incidents_version_end_transaction_id'), table_name='incidents_version')
    op.drop_index(op.f('ix_incidents_version_date'), table_name='incidents_version')
    op.drop_table('incidents_version')
    op.drop_index(op.f('ix_incident_links_version_transaction_id'), table_name='incident_links_version')
    op.drop_index(op.f('ix_incident_links_version_operation_type'), table_name='incident_links_version')
    op.drop_index(op.f('ix_incident_links_version_end_transaction_id'), table_name='incident_links_version')
    op.drop_table('incident_links_version')
    op.drop_index(op.f('ix_incident_license_plates_version_transaction_id'), table_name='incident_license_plates_version')
    op.drop_index(op.f('ix_incident_license_plates_version_operation_type'), table_name='incident_license_plates_version')
    op.drop_index(op.f('ix_incident_license_plates_version_end_transaction_id'), table_name='incident_license_plates_version')
    op.drop_table('incident_license_plates_version')
    op.drop_index(op.f('ix_faces_version_transaction_id'), table_name='faces_version')
    op.drop_index(op.f('ix_faces_version_operation_type'), table_name='faces_version')
    op.drop_index(op.f('ix_faces_version_end_transaction_id'), table_name='faces_version')
    op.drop_table('faces_version')
    op.drop_index(op.f('ix_descriptions_version_transaction_id'), table_name='descriptions_version')
    op.drop_index(op.f('ix_descriptions_version_operation_type'), table_name='descriptions_version')
    op.drop_index(op.f('ix_descriptions_version_end_transaction_id'), table_name='descriptions_version')
    op.drop_table('descriptions_version')
    op.drop_index(op.f('ix_assignments_version_transaction_id'), table_name='assignments_version')
    op.drop_index(op.f('ix_assignments_version_star_no'), table_name='assignments_version')
    op.drop_index(op.f('ix_assignments_version_star_date'), table_name='assignments_version')
    op.drop_index(op.f('ix_assignments_version_resign_date'), table_name='assignments_version')
    op.drop_index(op.f('ix_assignments_version_operation_type'), table_name='assignments_version')
    op.drop_index(op.f('ix_assignments_version_end_transaction_id'), table_name='assignments_version')
    op.drop_table('assignments_version')
    # ### end Alembic commands ###
